export type ProjectImage = readonly [src: string, title: string, description: string];

const archiveImage = (
  folder: "apartamentos" | "casas" | "comercial",
  index: number,
  title: string,
  description: string,
): ProjectImage => [
  `/images/portfolio-all/${folder}/${folder}-${String(index).padStart(3, "0")}.webp`,
  title,
  description,
];

const apartmentArchiveImages: ProjectImage[] = [
  archiveImage("apartamentos", 1, "Circulação com galeria de arte", "Marcenaria lateral, iluminação natural e composição afetiva"),
  archiveImage("apartamentos", 2, "Lavabo em madeira e pedra verde", "Espelho iluminado e materiais de presença marcante"),
  archiveImage("apartamentos", 3, "Cozinha linear com acabamento amadeirado", "Bancada contínua e organização para a rotina"),
  archiveImage("apartamentos", 4, "Cozinha em L com torre de eletros", "Aproveitamento das paredes e circulação desimpedida"),
  archiveImage("apartamentos", 5, "Varanda com jardim vertical", "Vegetação, balanço e área de descanso junto à vista"),
  archiveImage("apartamentos", 6, "Lavabo com pintura botânica", "Cor, desenho autoral e marcenaria suspensa"),
  archiveImage("apartamentos", 7, "Sala de jantar com cadeiras verdes", "Madeira clara, pendentes de vidro e integração visual"),
  archiveImage("apartamentos", 8, "Banheiro claro com box amplo", "Revestimentos neutros e marcenaria sob medida"),
  archiveImage("apartamentos", 9, "Estar e jantar integrados", "Painel contínuo de madeira e ambientes conectados"),
  archiveImage("apartamentos", 10, "Cozinha gourmet com estrutura metálica", "Ilha central, armazenamento aberto e uso compartilhado"),
  archiveImage("apartamentos", 11, "Suíte com painel de televisão", "Marcenaria de ponta a ponta e atmosfera acolhedora"),
  archiveImage("apartamentos", 12, "Cozinha compacta em tons claros", "Distribuição funcional em uma área reduzida"),
  archiveImage("apartamentos", 13, "Cozinha com ilha e banquetas", "Bancada para preparo, refeições rápidas e convivência"),
  archiveImage("apartamentos", 14, "Lavanderia integrada à cozinha", "Equipamentos embutidos e marcenaria leve"),
  archiveImage("apartamentos", 15, "Jantar com divisória de vidro", "Transparência entre os ambientes e luz preservada"),
  archiveImage("apartamentos", 16, "Entrada integrada à cozinha", "Painel de madeira organiza acesso e armazenamento"),
  archiveImage("apartamentos", 17, "Banheiro com revestimento geométrico", "Paginação em chevron e iluminação natural"),
  archiveImage("apartamentos", 18, "Varanda gourmet em tons escuros", "Cristaleira, adega e churrasqueira reunidas"),
  archiveImage("apartamentos", 19, "Brinquedoteca na varanda", "Espaço lúdico com mesa infantil e vista da cidade"),
  archiveImage("apartamentos", 20, "Quarto de bebê — vista geral", "Paleta neutra, berço, cômoda e poltrona organizados com suavidade"),
  archiveImage("apartamentos", 21, "Quarto de bebê — detalhe do berço", "Texturas delicadas e mobiliário preparado para a rotina de cuidado"),
  archiveImage("apartamentos", 22, "Sala com painel de madeira", "Televisão embutida e desenho horizontal do mobiliário"),
  archiveImage("apartamentos", 23, "Sala integrada à bancada gourmet", "Estar, refeições e cozinha no mesmo campo visual"),
  archiveImage("apartamentos", 24, "Hall com penteadeira suspensa", "Espelho orgânico e madeira aquecem a passagem"),
  archiveImage("apartamentos", 25, "Quarto infantil com marcenaria lúdica", "Nicho em forma de casa e armazenamento acessível"),
  archiveImage("apartamentos", 26, "Suíte com cabeceira azul", "Home office lateral e composição contemporânea"),
  archiveImage("apartamentos", 27, "Banheiro com revestimento preto", "Contraste, vegetação e iluminação zenital"),
  archiveImage("apartamentos", 28, "Varanda gourmet com adega", "Marcenaria cinza e equipamentos compactos"),
  archiveImage("apartamentos", 29, "Cozinha corredor com bancada", "Banquetas criam apoio sem comprometer a circulação"),
  archiveImage("apartamentos", 30, "Estar com estante vazada", "Marcenaria divide funções mantendo a integração"),
  archiveImage("apartamentos", 31, "Cozinha com mesa de apoio", "Bancada amadeirada aproxima preparo e refeições"),
  archiveImage("apartamentos", 32, "Sala com painel grafite", "Contraste entre madeira, tons escuros e luz natural"),
  archiveImage("apartamentos", 33, "Sala com sofá em L", "Conforto, painel ripado e amplo espaço de convivência"),
  archiveImage("apartamentos", 34, "Banheiro rosé — bancada dupla", "Vista geral com marcenaria amadeirada e box transparente"),
  archiveImage("apartamentos", 35, "Banheiro rosé — detalhe do box", "Nicho funcional e materiais de tonalidade suave prolongam a composição"),
  archiveImage("apartamentos", 36, "Quarto com marcenaria lateral", "Armários claros e composição serena"),
  archiveImage("apartamentos", 37, "Suíte com painel geométrico", "Televisão, penteadeira e armazenamento integrados"),
  archiveImage("apartamentos", 38, "Quarto jovem — vista geral", "Cama, bancada de estudos e armário em um layout flexível"),
  archiveImage("apartamentos", 39, "Quarto jovem — divisória móvel", "Painel deslizante cria privacidade e melhora o aproveitamento da área"),
  archiveImage("apartamentos", 40, "Quarto jovem — bancada de estudos", "Painel para memórias e nichos mantêm os objetos de uso diário organizados"),
  archiveImage("apartamentos", 41, "Quarto infantil azul", "Cabeceira lateral e prateleira para objetos afetivos"),
  archiveImage("apartamentos", 42, "Suíte em tons de verde", "Cabeceira ripada e armários de linhas discretas"),
  archiveImage("apartamentos", 43, "Quarto infantil com penteadeira", "Marcenaria contínua ao redor da janela"),
  archiveImage("apartamentos", 44, "Sala de estar — vista geral", "Tapete geométrico, madeira e mobiliário colorido organizam a composição"),
  archiveImage("apartamentos", 45, "Sala de estar — detalhe da poltrona", "Poltrona verde evidencia a materialidade e a iluminação do mesmo ambiente"),
  archiveImage("apartamentos", 46, "Cozinha branca com ilha", "Arte colorida e madeira pontuam a base neutra"),
  archiveImage("apartamentos", 47, "Jantar com serralheria e vidro", "Divisão leve entre cozinha e área social"),
  archiveImage("apartamentos", 48, "Banheiro infantil com nichos rosé", "Revestimento geométrico e armazenamento aberto"),
  archiveImage("apartamentos", 49, "Lavabo azul com madeira", "Curvas, espelho orgânico e luz indireta"),
  archiveImage("apartamentos", 50, "Lavabo com papel de parede botânico", "Estampa escura e bancada de pedra natural"),
  archiveImage("apartamentos", 51, "Corredor com painel ripado", "Galeria de quadros e iluminação de destaque"),
  archiveImage("apartamentos", 52, "Cozinha grafite com península", "Marcenaria escura e bancada para refeições"),
  archiveImage("apartamentos", 53, "Cozinha compacta verde", "Estrutura metálica, armários coloridos e mesa integrada"),
  archiveImage("apartamentos", 54, "Varanda gourmet revestida em pedra", "Churrasqueira, cristaleira e bancada de apoio"),
  archiveImage("apartamentos", 55, "Banheiro com madeira e mármore", "Espelho amplo e box iluminado naturalmente"),
  archiveImage("apartamentos", 56, "Sala ampla com sofá modular", "Integração com a cozinha e painel de madeira"),
  archiveImage("apartamentos", 57, "Sala de jantar junto à varanda", "Mesa orgânica, jardim vertical e luz abundante"),
  archiveImage("apartamentos", 58, "Banheiro branco com bancada amadeirada", "Texturas claras e desenho limpo"),
  archiveImage("apartamentos", 59, "Varanda com adega iluminada", "Marcenaria envidraçada e atmosfera noturna"),
];

const previousApartmentImages: ProjectImage[] = [
  ["/images/portfolio-quarto-infantil-rosa.webp", "Quarto infantil rosa", "Bancada de estudos e prateleiras ao alcance da criança"],
  ["/images/casas-hero.webp", "Sala integrada com pedra natural", "Jantar, estar e cozinha articulados por materiais claros"],
  ["/images/portfolio-quarto-beliche.webp", "Quarto infantil com beliche", "Escada com gavetas e marcenaria para brincar e guardar"],
  ["/images/apartamentos-hero.webp", "Apartamento com cozinha aberta", "Área social contínua e mobiliário em tons quentes"],
  ["/images/home-hero.webp", "Apartamento com circulação central", "Integração visual entre cozinha, jantar e estar"],
  ["/images/portfolio-varanda-pedra.webp", "Varanda gourmet com pedra natural", "Churrasqueira e cristaleira desenhadas para receber"],
  ["/images/portfolio-escritorio.webp", "Quarto multifuncional", "Home office e descanso separados por painel móvel"],
  ["/images/portfolio-cozinha.webp", "Cozinha gourmet na varanda", "Equipamentos compactos e bancada voltada para a vista"],
  ["/images/reformas-hero.webp", "Estar integrado à cozinha", "Madeira e marcenaria conectam os diferentes usos"],
  ["/images/portfolio-varanda.webp", "Varanda com banco e jardim vertical", "Canto de leitura banhado por luz natural"],
  ["/images/portfolio-quarto.webp", "Suíte com iluminação indireta", "Cabeceira acolhedora e composição simétrica"],
  ["/images/portfolio-cozinha-ilha.webp", "Cozinha com ilha e estante suspensa", "Estrutura metálica organiza utensílios e vegetação"],
  ["/images/portfolio-integracao-varanda.webp", "Sala conectada à varanda", "Jantar, estar e paisagem em uma composição contínua"],
  ["/images/portfolio-cozinha-cinza.webp", "Cozinha cinza com molduras", "Marcenaria clássica e pedra clara em equilíbrio"],
  ["/images/portfolio-lavabo-travertino.webp", "Lavabo em travertino e madeira", "Bancada esculpida e iluminação perimetral"],
  ["/images/portfolio-banheiro-verde.webp", "Banheiro verde com marcenaria clara", "Revestimento delicado e bancada funcional"],
  ["/images/portfolio-circulacao.webp", "Hall com linhas de luz", "Geometria luminosa valoriza a madeira"],
  ["/images/portfolio-home-office.webp", "Home office compacto", "Bancada sob medida junto à janela"],
];

export const apartmentImages: ProjectImage[] = [...apartmentArchiveImages, ...previousApartmentImages];

export const houseImages: ProjectImage[] = [
  archiveImage("casas", 1, "Fachada residencial com madeira", "Volumes brancos e paisagismo valorizam o acesso"),
  archiveImage("casas", 2, "Reforma de fachada urbana", "Atualização arquitetônica preservando a escala da rua"),
  archiveImage("casas", 3, "Casa com garagem em balanço", "Linhas horizontais e material cerâmico no térreo"),
  archiveImage("casas", 4, "Sala de jantar da casa", "Luminárias escultóricas e composição de quadros"),
  archiveImage("casas", 5, "Pátio com piscina e jardim", "Área íntima voltada para o lazer central"),
  archiveImage("casas", 6, "Varanda gourmet aberta à paisagem", "Estrutura de madeira e espaço generoso para receber"),
  archiveImage("casas", 7, "Área gourmet com lareira de pedra", "Cozinha externa integrada à varanda"),
  archiveImage("casas", 8, "Jantar com desenho contemporâneo", "Mesa de madeira e iluminação gráfica"),
  archiveImage("casas", 9, "Circulação com jardim vertical", "Paisagismo interno e luz atravessando os ambientes"),
  archiveImage("casas", 10, "Casa térrea com fachada amadeirada", "Implantação horizontal e acesso junto ao jardim"),
  archiveImage("casas", 11, "Passagem junto ao pátio", "Grandes esquadrias aproximam interior e exterior"),
  archiveImage("casas", 12, "Corredor com parede de pedra", "Textura natural e abertura para o jardim"),
  archiveImage("casas", 13, "Circulação iluminada à noite", "Pedra, seixos e luz indireta marcam o percurso"),
  archiveImage("casas", 14, "Fachada com pedra e pórtico escuro", "Entrada destacada por volumes e transparências"),
  archiveImage("casas", 15, "Fachada linear em pedra", "Cobertura leve e paisagismo de baixa manutenção"),
  archiveImage("casas", 16, "Casa com grandes planos de vidro", "Pedra natural e estrutura escura em contraste"),
  archiveImage("casas", 17, "Acesso principal com jardim", "Composição frontal valoriza a porta e as esquadrias"),
  archiveImage("casas", 18, "Fachada extensa com paisagismo", "Plano de pedra organiza a casa térrea"),
  archiveImage("casas", 19, "Casa com fachada em aço corten", "Geometria branca e acabamento oxidado"),
  archiveImage("casas", 20, "Estar voltado para a piscina", "Grandes aberturas conectam sala, jardim e lazer"),
  archiveImage("casas", 21, "Fachada urbana com portão metálico", "Privacidade e iluminação natural equilibradas"),
  archiveImage("casas", 22, "Casa contemporânea com pedra", "Pórtico preto e garagem integrada ao volume"),
  archiveImage("casas", 23, "Piscina junto ao pé-direito duplo", "Deck e área social conectados ao pátio"),
];

export const commercialImages: ProjectImage[] = [
  archiveImage("comercial", 1, "Fachada corporativa com brises", "Proteção solar e identidade arquitetônica"),
  archiveImage("comercial", 2, "Acesso de edifício comercial", "Marquise metálica e composição vertical"),
  archiveImage("comercial", 3, "Escritório com estações lineares", "Ergonomia, acústica e circulação organizada"),
  archiveImage("comercial", 4, "Restaurante com deck externo", "Fachada convidativa e área de atendimento aberta"),
  archiveImage("comercial", 5, "Sala individual de trabalho", "Bancada, armário e iluminação para concentração"),
  archiveImage("comercial", 6, "Apoio corporativo em madeira", "Armários, banco e vegetação em espaço compacto"),
  archiveImage("comercial", 7, "Hall de entrada corporativo", "Marcenaria amadeirada, espelho e iluminação integrada"),
  archiveImage("comercial", 8, "Fachada frontal do escritório", "Brises verticais reforçam a presença da marca"),
  archiveImage("comercial", 9, "Recepção corporativa — percurso de chegada", "Iluminação linear conduz o visitante até o atendimento"),
  archiveImage("comercial", 10, "Recepção corporativa — área de espera", "Jardim vertical e mobiliário criam acolhimento no mesmo ambiente"),
  archiveImage("comercial", 11, "Corredor de estações de trabalho", "Marcenaria contínua e passagem bem dimensionada"),
  archiveImage("comercial", 12, "Recepção corporativa — painel de atendimento", "Tons grafite, painel iluminado e percurso intuitivo reforçam a identidade"),
  archiveImage("comercial", 13, "Escritório corporativo — copa de apoio", "Marcenaria funcional para pausas e refeições rápidas da equipe"),
  ["/images/portfolio-varanda-preta.webp", "Circulação de escritório com apoio integrado", "Marcenaria, iluminação técnica e divisórias de vidro organizam o espaço"],
];
